### ISSUE TITLE
予約確定まで進んだ後のエラー対処について。

### ISSUE THREAD

**Issue by walnuts1018** [RyamNuts/Vaccine_reservation_for_V-yoyaku#2]
現在の予約ページの仕様により、20日以内でなくても予約確定ページに進めます。
しかし最後の確定ボタンを押すとエラーにより予約できません。
以前まではエラーメッセージを検出し、( `if len(driver.find_elements_by_xpath('//*[@id="modal-input-reserve-error-message-btn"]/p')) > 0:`)更新することで初めからやり直すことで問題はありませんでしたが、処理順番の入れ替え等によりエラーが出てしまうと予約処理を続けられなくなりました。

`if int(td.days) <=21:` の部分を大きくすることで先の日付にてテストできます。
予約ページまで遷移した後のテスト、修正をしていただける方がいらっしゃいましたらよろしくお願いします。

**Comment by argki** [comment]
### 予約可能日制限方法の変更
川崎市向けでは、会場によって20日先以降も予約を受け付けています。よって、20日以内の制限は```config.json```で設定ができるようにしたいと思っています。
https://github.com/Bioliss/Vaccine_reservation_for_V-yoyaku/tree/patch-1/config 最下部
### 予約確定ページまでの挙動の確認
残念ながら川崎市ではどの会場・日時も常時空きが出ず```×```表示の故、予約確定ページまで進める状況をなかなか再現できない環境です。
そのため、広島県向けの挙動についてもう少し詳しく確認させてください。
  * 予約確定ページに進める条件は、カレンダーの日付上に```△```または```○```が表示されている場合に限った話で合ってますでしょうか？
  * ```driver.find_element(By.ID, "btn_reservation_entry").click()``` の部分で alert が出力されることにより例外が発生してしまうと想像しているのですが、合ってますでしょうか？

**Comment by walnuts1018** [comment]
ご連絡ありがとうございます。
日付ページまで行けない状態なのですね。広島市におきましては少々空きがございますのでこちらで修正を行いたいと思います。

その後の挙動をお伝えしておきます。

カレンダーまでは表示できると思いますが、
その後予約したい日付をクリック（○もしくは△の場合のみクリックできます。）
すると接種時間を選択する画面となります。
![2021-09-04_08h52_45](https://user-images.githubusercontent.com/60650857/132075631-58d8a3d0-d052-4553-9e6f-a59d8b412c4b.png)


その後時間を選択する  (`driver.find_element(By.XPATH, "//*[@id='dayly-calendar-table']/tbody/tr["+str(uekara_num+1)+"]/td["+str(migikara_num)+"]/div/div").click() `  )と自動的に最終確定ページに遷移し、”予約を確定する”ボタンを押す (`driver.find_element(By.ID, "btn_reservation_entry").click()`)  ことで最終的に確定となります。
![2021-09-04_08h52_55](https://user-images.githubusercontent.com/60650857/132075644-6b59ffbb-f4e6-46cd-ad98-8d49131e912f.png)

しかし、予約可能期間外であったり、処理中に予約が埋まってしまうと、ページ上にエラーの要素  (`driver.find_elements_by_xpath('//*[@id="modal-input-reserve-error-message-btn"]/p')`)  が出てきます。
![2021-09-04_08h53_04](https://user-images.githubusercontent.com/60650857/132075648-84081e25-b063-43b7-a647-54c8f1443f9d.png)

ここまでが流れです。


##09/04/10:26追記
上記のエラー、また、時間選択画面に遷移したのちに"×"出会った場合も同様のことが起こっていたようなので修正しました。
fork先で機能追加をしていただけているようなのでそちらを修正していただけたらと思います。

あまり私は頻繁に機能修正等行えないかもしれないので、よろしければ貴方をこちらにコラボレーターとして招待いたします故、こちらに参加していただけたらと思っております。

**Comment by argki** [comment]
詳細な情報と修正、ありがとうございます。
おかげさまで想像でしか分からなかった挙動をしっかり把握することができました。
一旦forkの方にマージして、またプルリクしたいと思います。

また、招待いただきありがとうございます。

**Comment by walnuts1018** [comment]
こちらこそ協力してくださった事、誠に感謝申し上げます。
よろしくお願いします。
